version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm start
        ports:
            - 8080:3000
        environment:
            - MONGO_URL=mongodb://mongodb:27017/nestjs-app
        networks:
            - nestjs-network
        depends_on:
            - mongodb
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    mongodb: 
        image: mongo:latest
        container_name: mongodb
        volumes:
            - ./databases:/data/db
        ports:
            - 27017:27017
        networks:
            - nestjs-network
        restart: always

networks:
    nestjs-network:
        driver: bridge